Q1. Explain the concept of precision and recall in the context of classification models.

Q2. What is the F1 score and how is it calculated? How is it different from precision and recall?

Q3. What is ROC and AUC, and how are they used to evaluate the performance of classification models?

Q4. How do you choose the best metric to evaluate the performance of a classification model? What is multiclass classification and how is it different from binary classification?

Q5. Explain how logistic regression can be used for multiclass classification.

Q6. Describe the steps involved in an end-to-end project for multiclass classification.

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=35)

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_classifier = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_classifier.fit(X_train_scaled, y_train)

y_pred = svm_classifier.predict(X_test_scaled)

In [12]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=iris.target_names))

[[16  0  0]
 [ 0 13  1]
 [ 0  2 13]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       0.87      0.93      0.90        14
   virginica       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [13]:
# Creating a pickle file
import pickle
with open('model.pkl','wb') as f:
    pickle.dump(svm_classifier,f)

In [15]:
with open('model.pkl','rb') as g:
    k = pickle.load(g)

In [16]:
k

SVC(random_state=42)

Q7. What is model deployment and why is it important?

Q8. Explain how multi-cloud platforms are used for model deployment.

Q9. Discuss the benefits and challenges of deploying machine learning models in a multi-cloud environment.