# Numpy

In [2]:
 import numpy as np
 list_ = [1,2,3,4,5]
 array_list = np.array(object = list_)

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

The datatypes of both the variables are different. One is a list and other is an array

 Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [5]:
list_

[1, 2, 3, 4, 5]

In [6]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q3. Considering the following changes in the variable, array_list:

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

Shape
Size

In [17]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
num_array.shape

(2, 3)

In [16]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])