Q1. What are Eigenvalues and Eigenvectors? How are they related to the Eigen-Decomposition approach? Explain with an example.

In [1]:
import numpy as np
import pandas as pd

In [6]:
# Lets say we have a 2x2 matrix

In [22]:
A = np.matrix([[4,1],[2,3]])

In [23]:
A

matrix([[4, 1],
        [2, 3]])

In [24]:
# We will split this matrix into eigenvector and eigenvalues

# For eigen values:

A - lambda*I = 0

In [25]:
I  = np.eye(2)

In [26]:
I

array([[1., 0.],
       [0., 1.]])

We will apply A - lambda*I = 0

From here, we will get two values of lambda, 5 and 2.

# For eigen vectors

A - lambda(I)

here, we will take lambda as both 5 and 2 separately to get two eigen vectors

In [27]:
# We will get the below mentioned eigenvectors:

EV1 = np.matrix([[1],[1]])
EV2 = np.matrix([[1],[-2]])

In [28]:
EV1, EV2

(matrix([[1],
         [1]]),
 matrix([[ 1],
         [-2]]))

Q2. What is eigen decomposition and what is its significance in linear algebra?

Q3. What are the conditions that must be satisfied for a square matrix to be diagonalizable using the Eigen-Decomposition approach? Provide a brief proof to support your answer.

What is the significance of the spectral theorem in the context of the Eigen-Decomposition approach? How is it related to the diagonalizability of a matrix? Explain with an example.

EXAMPLE: 

In [31]:
M = np.matrix([[4,1],[2,3]])

In [33]:
M

matrix([[4, 1],
        [2, 3]])

# For calculating eigenvalues:

M - λ*(I) = 0

From here, we will find out two eigenvalue, 5 and 2. 

# For calculating eigenvectors:

M - λ*(I) = 0

we will put both the values 5 and 2 separately to get two different eigenvectors

In [37]:
EV_1 = np.matrix([[1],[1]])
EV_2 = np.matrix([[1],[-2]])

In [38]:
EV_1,EV_2

(matrix([[1],
         [1]]),
 matrix([[ 1],
         [-2]]))

# Now, we will normalize eigenvectors

In [39]:
norm_vec1 = EV_1/np.sqrt(2)

In [40]:
norm_vec2 = EV_2/np.sqrt(2)

In [41]:
norm_vec1

matrix([[0.70710678],
        [0.70710678]])

In [42]:
norm_vec2

matrix([[ 0.70710678],
        [-1.41421356]])

In [43]:
#Also, we have the following matrices:
 
Diagonal = np.matrix([[5,0],[0,2]])

In [44]:
Diagonal

matrix([[5, 0],
        [0, 2]])

In [48]:
Orthogonal_Matrix = np.matrix([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])

In [49]:
Orthogonal_Matrix

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [52]:
Ortho_trans = Orthogonal_Matrix.transpose()

In [53]:
Ortho_trans

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

# To verify the diagonlization

M = PDP[t]

Q5. How do you find the eigenvalues of a matrix and what do they represent?

In [54]:
M

matrix([[4, 1],
        [2, 3]])

Q8. What are some real-world applications of eigen decomposition?

Q9. Can a matrix have more than one set of eigenvectors and eigenvalues?

Q10. In what ways is the Eigen-Decomposition approach useful in data analysis and machine learning? Discuss at least three specific applications or techniques that rely on Eigen-Decomposition.